### NumPy Practice – Day 2 (Thinking More)

**Setup**

1. Create a NumPy array called `A` of shape `(6, 12)`.
2. Fill it with random integers between 10 and 200.



In [71]:
import numpy as np

In [72]:
def resetA():
    np.random.seed(42)
    global A
    A = np.random.randint(10,201,size=(6,12))
resetA()

### Part 1: Precision Indexing

1. Extract the 2nd, 4th, and 6th rows only (in that order).
2. Extract columns 0, 3, 7, and 11.
3. From the whole matrix, extract a submatrix containing:

   * rows 1 to 4
   * every 2nd column
4. Get the bottom-right 3×4 block.

In [73]:
A

array([[112, 189, 102,  24, 116,  81, 198,  30, 112, 131,  84,  97],
       [126, 109, 113, 161, 140, 159,  62,  11,  97, 167,  47, 139],
       [197,  30, 170,  67,  31,  98,  58,  68, 179, 197,  24, 199],
       [199, 184, 199,  60, 117,  64,  73, 140,  60, 144,  30,  82],
       [176,  27, 141,  98,  69,  23,  18,  99,  62, 139,  93, 101],
       [120, 197, 181,  17, 184,  44,  90, 173,  59, 113, 141,  11]],
      dtype=int32)

In [83]:
# Q1
A[[1,3,5]]

array([[126, 109, 113, 161, 140, 159,  62,  11,  97, 167,  47, 139],
       [199, 184, 199,  60, 117,  64,  73, 140,  60, 144,  30,  82],
       [120, 197, 181,  17, 184,  44,  90, 173,  59, 113, 141,  11]],
      dtype=int32)

In [75]:
# Q2
A[np.arange(6)[:,None],np.array([0,3,7,11])]

array([[112,  24,  30,  97],
       [126, 161,  11, 139],
       [197,  67,  68, 199],
       [199,  60, 140,  82],
       [176,  98,  99, 101],
       [120,  17, 173,  11]], dtype=int32)

In [76]:
# Q3
A[np.array([0,1,2,3])[:,None],1]

array([[189],
       [109],
       [ 30],
       [184]], dtype=int32)

In [ ]:
# Q4
A[np.arange(3,6)[:,None],np.arange(8,12)]

### Part 2: Smart Slicing

5. Reverse only the middle 4 rows.
6. Keep the first half of columns, discard the rest.
7. Swap the first and last rows.
8. Swap the first and last columns.

In [90]:
# Q5
A[1:5]=A[4:0:-1]
print(A)
resetA()

[[112 189 102  24 116  81 198  30 112 131  84  97]
 [176  27 141  98  69  23  18  99  62 139  93 101]
 [199 184 199  60 117  64  73 140  60 144  30  82]
 [197  30 170  67  31  98  58  68 179 197  24 199]
 [126 109 113 161 140 159  62  11  97 167  47 139]
 [120 197 181  17 184  44  90 173  59 113 141  11]]


In [84]:
# Q6
A[:,:6]

array([[112, 189, 102,  24, 116,  81, 198],
       [126, 109, 113, 161, 140, 159,  62],
       [197,  30, 170,  67,  31,  98,  58],
       [199, 184, 199,  60, 117,  64,  73],
       [176,  27, 141,  98,  69,  23,  18],
       [120, 197, 181,  17, 184,  44,  90]], dtype=int32)

In [91]:
# Q7
A[0::5] = A[5::-5]
print(A)
resetA()

[[120 197 181  17 184  44  90 173  59 113 141  11]
 [126 109 113 161 140 159  62  11  97 167  47 139]
 [197  30 170  67  31  98  58  68 179 197  24 199]
 [199 184 199  60 117  64  73 140  60 144  30  82]
 [176  27 141  98  69  23  18  99  62 139  93 101]
 [112 189 102  24 116  81 198  30 112 131  84  97]]


In [101]:
# Q8
A[:,0::11] = A[:,-1::-11]
print(A)
resetA()

[[ 97 189 102  24 116  81 198  30 112 131  84 112]
 [139 109 113 161 140 159  62  11  97 167  47 126]
 [199  30 170  67  31  98  58  68 179 197  24 197]
 [ 82 184 199  60 117  64  73 140  60 144  30 199]
 [101  27 141  98  69  23  18  99  62 139  93 176]
 [ 11 197 181  17 184  44  90 173  59 113 141 120]]



### Part 3: Boolean & Mask Logic

9. Create a mask for values divisible by 5.
10. Set all values greater than 150 to 999.
11. Extract elements that are:

    * greater than 50
    * AND less than 120
12. Count how many elements are even.


In [102]:
# Q9
A%5==0

array([[False, False, False, False, False, False, False,  True, False,
        False, False, False],
       [False, False, False, False,  True, False, False, False, False,
        False, False, False],
       [False,  True,  True, False, False, False, False, False, False,
        False, False, False],
       [False, False, False,  True, False, False, False,  True,  True,
        False,  True, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False],
       [ True, False, False, False, False, False,  True, False, False,
        False, False, False]])

In [105]:
# Q10
A[A>50]=999
print(A)
resetA()

[[999 999 999  24 999 999 999  30 999 999 999 999]
 [999 999 999 999 999 999 999  11 999 999  47 999]
 [999  30 999 999  31 999 999 999 999 999  24 999]
 [999 999 999 999 999 999 999 999 999 999  30 999]
 [999  27 999 999 999  23  18 999 999 999 999 999]
 [999 999 999  17 999  44 999 999 999 999 999  11]]


In [106]:
# Q11
A[(A>50) & (A<120)]

array([112, 102, 116,  81, 112,  84,  97, 109, 113,  62,  97,  67,  98,
        58,  68,  60, 117,  64,  73,  60,  82,  98,  69,  99,  62,  93,
       101,  90,  59, 113], dtype=int32)

In [107]:
# Q12
A[A%2==0].shape[0]

33

### Part 4: Sorting With Control

13. Sort only the last 3 columns of the array (column-wise).
14. Sort rows based on their maximum value.
15. Sort rows based on their mean value.
16. For each column, find the index of its smallest value.


In [109]:
# Q13
A[:,-1:-4:-1]=np.sort(A[:,9:],axis=0)
print(A)
resetA()

[[112 189 102  24 116  81 198  30 112 113  24  11]
 [126 109 113 161 140 159  62  11  97 131  30  82]
 [197  30 170  67  31  98  58  68 179 139  47  97]
 [199 184 199  60 117  64  73 140  60 144  84 101]
 [176  27 141  98  69  23  18  99  62 167  93 139]
 [120 197 181  17 184  44  90 173  59 197 141 199]]


In [116]:
# Q14
a = np.sum(A,axis=1)
b = np.argsort(a)
A[b]

array([[176,  27, 141,  98,  69,  23,  18,  99,  62, 139,  93, 101],
       [112, 189, 102,  24, 116,  81, 198,  30, 112, 131,  84,  97],
       [197,  30, 170,  67,  31,  98,  58,  68, 179, 197,  24, 199],
       [120, 197, 181,  17, 184,  44,  90, 173,  59, 113, 141,  11],
       [126, 109, 113, 161, 140, 159,  62,  11,  97, 167,  47, 139],
       [199, 184, 199,  60, 117,  64,  73, 140,  60, 144,  30,  82]],
      dtype=int32)

In [119]:
# Q15
a = np.mean(A,axis=1)
b = np.argsort(a)
A[b]

array([[176,  27, 141,  98,  69,  23,  18,  99,  62, 139,  93, 101],
       [112, 189, 102,  24, 116,  81, 198,  30, 112, 131,  84,  97],
       [197,  30, 170,  67,  31,  98,  58,  68, 179, 197,  24, 199],
       [120, 197, 181,  17, 184,  44,  90, 173,  59, 113, 141,  11],
       [126, 109, 113, 161, 140, 159,  62,  11,  97, 167,  47, 139],
       [199, 184, 199,  60, 117,  64,  73, 140,  60, 144,  30,  82]],
      dtype=int32)

In [134]:
# Q16
a = np.argsort(A,axis=0)
a[:,0].shape

(6,)

### Part 5: Thinking Section 🧠

17. Without using loops:

* For each row, subtract the row mean from every element.

18. Reorder columns based on the sorted order of the last row.
19. Keep only the largest 2 values per column; set the rest to -1.
20. Create a new matrix where:

* rows with sum > overall mean sum are kept
* others are removed.

In [140]:
# Q17
a = np.mean(A,axis=1)[:,None]
A-a


array([[  5.66666667,  82.66666667,  -4.33333333, -82.33333333,
          9.66666667, -25.33333333,  91.66666667, -76.33333333,
          5.66666667,  24.66666667, -22.33333333,  -9.33333333],
       [ 15.08333333,  -1.91666667,   2.08333333,  50.08333333,
         29.08333333,  48.08333333, -48.91666667, -99.91666667,
        -13.91666667,  56.08333333, -63.91666667,  28.08333333],
       [ 87.16666667, -79.83333333,  60.16666667, -42.83333333,
        -78.83333333, -11.83333333, -51.83333333, -41.83333333,
         69.16666667,  87.16666667, -85.83333333,  89.16666667],
       [ 86.33333333,  71.33333333,  86.33333333, -52.66666667,
          4.33333333, -48.66666667, -39.66666667,  27.33333333,
        -52.66666667,  31.33333333, -82.66666667, -30.66666667],
       [ 88.83333333, -60.16666667,  53.83333333,  10.83333333,
        -18.16666667, -64.16666667, -69.16666667,  11.83333333,
        -25.16666667,  51.83333333,   5.83333333,  13.83333333],
       [  9.16666667,  86.16666667,

In [149]:
# Q18
a = np.argsort(A[-1])
A[:,a]

array([[ 97,  24,  81, 112, 198, 131, 112,  84,  30, 102, 116, 189],
       [139, 161, 159,  97,  62, 167, 126,  47,  11, 113, 140, 109],
       [199,  67,  98, 179,  58, 197, 197,  24,  68, 170,  31,  30],
       [ 82,  60,  64,  60,  73, 144, 199,  30, 140, 199, 117, 184],
       [101,  98,  23,  62,  18, 139, 176,  93,  99, 141,  69,  27],
       [ 11,  17,  44,  59,  90, 113, 120, 141, 173, 181, 184, 197]],
      dtype=int32)

In [183]:
# Q19
a = np.argsort(A,axis=0)[4:].T
b = np.zeros_like(A)
b[a,np.arange(12)[:,None]]=1
mask=b<1
A[mask]=0
print(A)
resetA()

[[  0 189   0   0   0   0 198   0 112   0   0   0]
 [  0   0   0 161 140 159   0   0   0 167   0 139]
 [197   0   0   0   0  98   0   0 179 197   0 199]
 [199   0 199   0   0   0   0 140   0   0   0   0]
 [  0   0   0  98   0   0   0   0   0   0  93   0]
 [  0 197 181   0 184   0  90 173   0   0 141   0]]


In [184]:
# Q20
mask1 = np.sum(A,axis=1) > np.sum(np.mean(A,axis=1)) # Since it says mean sum , I will assume its the sum of all the row mean
A[mask1]

array([[112, 189, 102,  24, 116,  81, 198,  30, 112, 131,  84,  97],
       [126, 109, 113, 161, 140, 159,  62,  11,  97, 167,  47, 139],
       [197,  30, 170,  67,  31,  98,  58,  68, 179, 197,  24, 199],
       [199, 184, 199,  60, 117,  64,  73, 140,  60, 144,  30,  82],
       [176,  27, 141,  98,  69,  23,  18,  99,  62, 139,  93, 101],
       [120, 197, 181,  17, 184,  44,  90, 173,  59, 113, 141,  11]],
      dtype=int32)