### Problem 1 – Global Ranking + Structure

1. Create a matrix D of shape (10, 12), values between -100 and 200.
2. Replace all negative values with the median of the entire matrix.
3. Keep only the top 20% largest values per column, set the rest to 0.
4. Reorder rows based on their variance (highest variance first).
5. Create a new matrix containing only rows whose maximum value is above the 90th percentile of the entire matrix.

In [1]:
import numpy as np

In [76]:
#1
def resetD():
    np.random.seed(42)
    global D
    D = np.random.randint(-100,200,size=(10,12))

In [69]:
#2
print(np.where(D<0,np.median(D),D))
print("Median:",np.median(D))

[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 55.   0. 173.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0. 165.   0.   0. 187. 199.   0. 137.   0.   0.   0.]
 [  0.   0.   0. 119.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0. 168.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0. 144. 199. 188. 197.]
 [  0.   0.   0.   0.   0.   0. 192.   0.   0. 185. 112.   0.]
 [ 94. 195.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0. 177.   0. 196.   0.  90.   0.   0.   0. 130.]
 [  0. 192.   0.   0. 182.   0.   0. 142.   0.   0.   0.   0.]]
Median: 0.0


In [101]:
#3
col_length = D.shape[0]
percent20 = np.int64(col_length * (20/100))

a = np.arange(0,12)
multiplier = np.ones((8,12))

c = np.int64(np.multiply(a,multiplier))
b = np.argsort(D,axis=0)[:8]

D[b,c]=0
print(D)

# I did this by advanced indexing , getting the indices of values which are not the 2 two largest values of that column and setting it to 0


[[  0 170   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0 193   0 176  60   0 152   0   0   0]
 [  0   0 170   0   0   0   0   0   0   0   0   0]
 [173   0   0   0 164   0   0 163   0   0   0   0]
 [  0   0   0 159   0   0   0   0   0 169   0 114]
 [151   0 195   0   0   0   0 179   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0 188 160]
 [  0   0   0   0   0 167   0   0   0   0 192   0]
 [  0 113   0   0   0   0 156   0   0 154   0   0]
 [  0   0   0   0 130   0   0   0 121   0   0   0]]


In [88]:
np.argsort(D,axis=0)

array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 2, 1, 2, 1, 2, 2, 1, 2, 1, 1, 1],
       [2, 3, 3, 3, 2, 3, 3, 2, 3, 2, 2, 2],
       [4, 4, 4, 5, 4, 4, 4, 4, 4, 3, 3, 3],
       [7, 6, 7, 7, 6, 6, 6, 7, 6, 5, 4, 5],
       [6, 5, 6, 6, 5, 5, 5, 6, 5, 6, 5, 7],
       [9, 7, 9, 9, 7, 9, 7, 9, 7, 7, 9, 9],
       [8, 9, 8, 8, 8, 8, 9, 8, 8, 9, 8, 8],
       [5, 8, 2, 4, 9, 7, 1, 3, 9, 8, 6, 4],
       [3, 0, 5, 1, 3, 1, 8, 5, 1, 4, 7, 6]])

In [89]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [90]:
b

array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 2, 1, 2, 1, 2, 2, 1, 2, 1, 1, 1],
       [2, 3, 3, 3, 2, 3, 3, 2, 3, 2, 2, 2],
       [4, 4, 4, 5, 4, 4, 4, 4, 4, 3, 3, 3],
       [7, 6, 7, 7, 6, 6, 6, 7, 6, 5, 4, 5],
       [6, 5, 6, 6, 5, 5, 5, 6, 5, 6, 5, 7],
       [9, 7, 9, 9, 7, 9, 7, 9, 7, 7, 9, 9],
       [8, 9, 8, 8, 8, 8, 9, 8, 8, 9, 8, 8]])

In [91]:
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [92]:
#4
resetD()
rowVar = np.var(D,axis=1)
mask = np.argsort(rowVar)
D[mask]

array([[  2, 170,   6, -29,  88, -80,   2,  21, 114, -13,  -1,  51],
       [ 69,  87, 170,  89,  74, -50, -46, 143,  30,  34, -80,  66],
       [151,  89, 195, 112, 107, 136, -48, 179, 116, 151,  87, -60],
       [ 56, -86, -36, -92,  28,  35, -38,  38, -20,  62, 188, 160],
       [-86, -59,  78, -38, 130, 140, -49,  -5, 121, 130, 136,  42],
       [ 71, 113, -66, 126,   0,  30, 156, -96, 117, 154, 182, 106],
       [-99, -47,   5, 159,  90, 117, -57,  61, 101, 169, 170, 114],
       [ 30,  49, 157, 193,  91, 176,  60, -79, 152, 135, -52, -42],
       [130, -60, -73,  34, 100, 167, -68, -53, -39, 115, 192,  -2],
       [173, -12, -87, 141, 164, -48,  -9, 163, -66, 105, -20, -51]],
      dtype=int32)

In [105]:
#5
percent90 = np.int64(np.multiply(*D.shape) * 0.9) # 12 * 9 
percent90Value = np.sort(D.reshape(-1))[percent90]

In [106]:
percent90Value

np.int32(164)

In [ ]:
# This return a boolean mask where value > percent90Value=164
a=D>percent90Value

# Summing on the mask a along the axis , True = 1 , False = 0 . So any rows with all False will have sum 0 , meaning that rows value dont satisfy a
am = np.sum(a,axis=1)
am

array([1, 2, 1, 1, 1, 2, 1, 2, 0, 0])

In [ ]:
# Converitng am to mask / Rows to display 
mask = am > 0
mask

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
       False])

In [117]:
D[mask]

array([[  0, 170,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0, 193,   0, 176,  60,   0, 152,   0,   0,   0],
       [  0,   0, 170,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [173,   0,   0,   0, 164,   0,   0, 163,   0,   0,   0,   0],
       [  0,   0,   0, 159,   0,   0,   0,   0,   0, 169,   0, 114],
       [151,   0, 195,   0,   0,   0,   0, 179,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 188, 160],
       [  0,   0,   0,   0,   0, 167,   0,   0,   0,   0, 192,   0]],
      dtype=int32)