### Problem 1 – Global Ranking + Structure

1. Create a matrix D of shape (10, 12), values between -100 and 200.
2. Replace all negative values with the median of the entire matrix.
3. Keep only the top 20% largest values per column, set the rest to 0.
4. Reorder rows based on their variance (highest variance first).
5. Create a new matrix containing only rows whose maximum value is above the 90th percentile of the entire matrix.

In [102]:
import numpy as np

In [103]:
#1
def resetD():
    np.random.seed(42)
    global D
    D = np.random.randint(-100,200,size=(10,12))
    D = D.astype(np.float64)
resetD()


In [104]:
#2
print(np.where(D<0,np.median(D),D))
print("Median:",np.median(D))

[[  2.  170.    6.   61.5  88.   61.5   2.   21.  114.   61.5  61.5  51. ]
 [ 30.   49.  157.  193.   91.  176.   60.   61.5 152.  135.   61.5  61.5]
 [ 69.   87.  170.   89.   74.   61.5  61.5 143.   30.   34.   61.5  66. ]
 [173.   61.5  61.5 141.  164.   61.5  61.5 163.   61.5 105.   61.5  61.5]
 [ 61.5  61.5   5.  159.   90.  117.   61.5  61.  101.  169.  170.  114. ]
 [151.   89.  195.  112.  107.  136.   61.5 179.  116.  151.   87.   61.5]
 [ 56.   61.5  61.5  61.5  28.   35.   61.5  38.   61.5  62.  188.  160. ]
 [130.   61.5  61.5  34.  100.  167.   61.5  61.5  61.5 115.  192.   61.5]
 [ 71.  113.   61.5 126.    0.   30.  156.   61.5 117.  154.  182.  106. ]
 [ 61.5  61.5  78.   61.5 130.  140.   61.5  61.5 121.  130.  136.   42. ]]
Median: 61.5


In [105]:
#3
col_length = D.shape[0]
percent20 = np.int64(col_length * (20/100))

a = np.arange(0,12)
multiplier = np.ones((8,12))

c = np.int64(np.multiply(a,multiplier))
b = np.argsort(D,axis=0)[:8]

D[b,c]=0
print(D)

# I did this by advanced indexing , getting the indices of values which are not the 2 two largest values of that column and setting it to 0


[[  0. 170.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0. 193.   0. 176.  60.   0. 152.   0.   0.   0.]
 [  0.   0. 170.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [173.   0.   0.   0. 164.   0.   0. 163.   0.   0.   0.   0.]
 [  0.   0.   0. 159.   0.   0.   0.   0.   0. 169.   0. 114.]
 [151.   0. 195.   0.   0.   0.   0. 179.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 188. 160.]
 [  0.   0.   0.   0.   0. 167.   0.   0.   0.   0. 192.   0.]
 [  0. 113.   0.   0.   0.   0. 156.   0.   0. 154.   0.   0.]
 [  0.   0.   0.   0. 130.   0.   0.   0. 121.   0.   0.   0.]]


In [106]:
np.argsort(D,axis=0)

array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 2, 1, 2, 1, 2, 2, 1, 2, 1, 1, 1],
       [2, 3, 3, 3, 2, 3, 3, 2, 3, 2, 2, 2],
       [4, 4, 4, 5, 4, 4, 4, 4, 4, 3, 3, 3],
       [7, 6, 7, 7, 6, 6, 6, 7, 6, 5, 4, 5],
       [6, 5, 6, 6, 5, 5, 5, 6, 5, 6, 5, 7],
       [9, 7, 9, 9, 7, 9, 7, 9, 7, 7, 9, 9],
       [8, 9, 8, 8, 8, 8, 9, 8, 8, 9, 8, 8],
       [5, 8, 2, 4, 9, 7, 1, 3, 9, 8, 6, 4],
       [3, 0, 5, 1, 3, 1, 8, 5, 1, 4, 7, 6]])

In [107]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [108]:
b

array([[4, 6, 3, 6, 8, 0, 7, 8, 3, 0, 2, 5],
       [9, 7, 7, 9, 6, 2, 4, 1, 7, 2, 1, 3],
       [0, 9, 8, 0, 2, 3, 9, 7, 6, 6, 3, 1],
       [1, 4, 6, 7, 0, 8, 5, 9, 2, 3, 0, 7],
       [6, 3, 4, 2, 4, 6, 2, 0, 4, 7, 5, 9],
       [2, 1, 0, 5, 1, 4, 6, 6, 0, 9, 9, 0],
       [8, 2, 9, 8, 7, 5, 3, 4, 5, 1, 4, 2],
       [7, 5, 1, 3, 5, 9, 0, 2, 8, 5, 8, 8]])

In [109]:
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [110]:
#4
resetD()
rowVar = np.var(D,axis=1)
mask = np.argsort(rowVar)
D[mask]

array([[  2., 170.,   6., -29.,  88., -80.,   2.,  21., 114., -13.,  -1.,
         51.],
       [ 69.,  87., 170.,  89.,  74., -50., -46., 143.,  30.,  34., -80.,
         66.],
       [151.,  89., 195., 112., 107., 136., -48., 179., 116., 151.,  87.,
        -60.],
       [ 56., -86., -36., -92.,  28.,  35., -38.,  38., -20.,  62., 188.,
        160.],
       [-86., -59.,  78., -38., 130., 140., -49.,  -5., 121., 130., 136.,
         42.],
       [ 71., 113., -66., 126.,   0.,  30., 156., -96., 117., 154., 182.,
        106.],
       [-99., -47.,   5., 159.,  90., 117., -57.,  61., 101., 169., 170.,
        114.],
       [ 30.,  49., 157., 193.,  91., 176.,  60., -79., 152., 135., -52.,
        -42.],
       [130., -60., -73.,  34., 100., 167., -68., -53., -39., 115., 192.,
         -2.],
       [173., -12., -87., 141., 164., -48.,  -9., 163., -66., 105., -20.,
        -51.]])

In [111]:
#5
percent90 = np.int64(np.multiply(*D.shape) * 0.9) # 12 * 9 
percent90Value = np.sort(D.reshape(-1))[percent90]

In [112]:
percent90Value

np.float64(169.0)

In [113]:
# This return a boolean mask where value > percent90Value=164
a=D>percent90Value

# Summing on the mask a along the axis , True = 1 , False = 0 . So any rows with all False will have sum 0 , meaning that rows value dont satisfy a
am = np.sum(a,axis=1)
am

array([1, 2, 1, 1, 1, 2, 1, 1, 1, 0])

In [114]:
# Converitng am to mask / Rows to display 
mask = am > 0
mask

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False])

In [115]:
D[mask]

array([[  2., 170.,   6., -29.,  88., -80.,   2.,  21., 114., -13.,  -1.,
         51.],
       [ 30.,  49., 157., 193.,  91., 176.,  60., -79., 152., 135., -52.,
        -42.],
       [ 69.,  87., 170.,  89.,  74., -50., -46., 143.,  30.,  34., -80.,
         66.],
       [173., -12., -87., 141., 164., -48.,  -9., 163., -66., 105., -20.,
        -51.],
       [-99., -47.,   5., 159.,  90., 117., -57.,  61., 101., 169., 170.,
        114.],
       [151.,  89., 195., 112., 107., 136., -48., 179., 116., 151.,  87.,
        -60.],
       [ 56., -86., -36., -92.,  28.,  35., -38.,  38., -20.,  62., 188.,
        160.],
       [130., -60., -73.,  34., 100., 167., -68., -53., -39., 115., 192.,
         -2.],
       [ 71., 113., -66., 126.,   0.,  30., 156., -96., 117., 154., 182.,
        106.]])

### Problem 2 – Constraint Logic

Using the same matrix D:
1. Normalize each row by subtracting its row mean and dividing by its row standard deviation.
2. Remove columns where more than 40% of values are zero.
3. From the remaining matrix, extract the submatrix formed by:
    - rows with positive mean
    - columns whose maximum is above the overall mean

This forces dimension-based conditional logic.

---

Doing 

```
D -= row_mean
D = row_std/D
```
in two steps because 

$$\frac{(a-b)}{c} = \left(\frac{a}{c}-\frac{b}{c}\right) \: \neq \: \frac{ca - b}{c} = a - \frac{b}{c}$$

In [116]:
#1
row_mean = np.mean(D,axis=1)[:,None]
row_std = np.mean(D,axis=1)[:,None]

D -= row_mean
D = row_std/D
D


array([[ -1.0781759 ,   0.19368051,  -1.27799228,  -0.48748159,
          0.45655172,  -0.2563904 ,  -1.0781759 ,  -4.18987342,
          0.31918997,  -0.67967146,  -0.96501458,   1.17793594],
       [ -1.70588235,  -3.08510638,   0.85798817,   0.60165975,
          3.91891892,   0.70048309,  -5.8       ,  -0.47854785,
          0.91194969,   1.16      ,  -0.58232932,  -0.63318777],
       [  2.4214876 ,   1.27947598,   0.40302613,   1.21576763,
          1.94039735,  -0.49409781,  -0.51493849,   0.51858407,
         -2.59292035,  -3.29213483,  -0.37904269,   2.84466019],
       [  0.27911275,  -0.75879397,  -0.30260521,   0.36561743,
          0.2990099 ,  -0.44023324,  -0.80748663,   0.30139721,
         -0.36385542,   0.56133829,  -0.65367965,  -0.42535211],
       [ -0.39726027,  -0.58129176,  -1.08298755,   0.696     ,
          2.63636364,   1.26086957,  -0.53374233, -15.35294118,
          1.82517483,   0.62891566,   0.62291169,   1.33846154],
       [  2.03517588,  -8.26530612,

In [117]:
#2
percent40ValuesCount = D.shape[0] * 0.4
cond = D == 0
mask = np.sum(cond,axis=0) != 4
D[:,mask]

array([[ -1.0781759 ,   0.19368051,  -1.27799228,  -0.48748159,
          0.45655172,  -0.2563904 ,  -1.0781759 ,  -4.18987342,
          0.31918997,  -0.67967146,  -0.96501458,   1.17793594],
       [ -1.70588235,  -3.08510638,   0.85798817,   0.60165975,
          3.91891892,   0.70048309,  -5.8       ,  -0.47854785,
          0.91194969,   1.16      ,  -0.58232932,  -0.63318777],
       [  2.4214876 ,   1.27947598,   0.40302613,   1.21576763,
          1.94039735,  -0.49409781,  -0.51493849,   0.51858407,
         -2.59292035,  -3.29213483,  -0.37904269,   2.84466019],
       [  0.27911275,  -0.75879397,  -0.30260521,   0.36561743,
          0.2990099 ,  -0.44023324,  -0.80748663,   0.30139721,
         -0.36385542,   0.56133829,  -0.65367965,  -0.42535211],
       [ -0.39726027,  -0.58129176,  -1.08298755,   0.696     ,
          2.63636364,   1.26086957,  -0.53374233, -15.35294118,
          1.82517483,   0.62891566,   0.62291169,   1.33846154],
       [  2.03517588,  -8.26530612,

In [118]:
#3
# We need to make two masks
# Row mask and column mask 
# D[np.mean(D,axis=1) > 0,np.max(D,axis=0) > np.mean(D)] # This didn't work cause numpy tryna zip two arrays but they are not of same length
D[np.mean(D,axis=1) > 0][:,np.max(D,axis=0) > np.mean(D)] # apply masks one by one


array([[ 2.4214876 ,  1.27947598,  0.40302613,  1.21576763,  1.94039735,
        -0.49409781, -0.51493849,  0.51858407, -2.59292035, -3.29213483,
        -0.37904269,  2.84466019],
       [ 2.03517588, -8.26530612,  1.08      ,  9.41860465, 17.60869565,
         2.91366906, -0.67839196,  1.3022508 ,  6.86440678,  2.03517588,
        -7.10526316, -0.62790698],
       [ 0.78249337, -0.22230595, -0.40577717, -0.2108649 ,  7.19512195,
         2.36      , -0.39280959,  1.83229814, -0.55140187,  0.65701559,
         0.15043345,  0.18153846]])

In [119]:
np.mean(D,axis=1) > 0

array([False, False,  True, False, False,  True,  True, False, False,
       False])

In [120]:
# rough
#D[[4,5,5,7],[1,2,3]]

### Problem 3 – Data-Style Mini Task (Student Scores)

Simulate a dataset:

Rows = 50 students,
Columns = 6 subjects,
Scores between 0 and 100

Call it scores.

Now:

1. Remove students whose average score is below the global median average.
2. Rank students by their worst subject (descending).
3. For each subject, find the top 5 students.
4. Create a matrix that keeps only:

    - students in the top 30% overall average

    - but only their top 3 subject scores (others set to 0).

That’s realistic manipulation.

```markdown
I had to use structured array because in question 3 ,I had to find the top 5 students , student scores can't tell us who the student is .
So I made the stuctured arrays to have umm something represent the student .( could have been done without structured arrays as well since the roll no is int)
but manipulation in a structured array was hard so I had to extract the scores and keep it in an array , altho i already had such a array , i extracted it from strucutred array because I made it so I had to use it
```

In [121]:
subjects = [('roll no',np.int64),
            ('ala',np.int32),
            ('agt',np.int32),
            ('ca',np.int32),
            ('E waste',np.int32),
            ('green chem',np.int32),
            ('rm',np.int32)]
scores0 = np.random.randint(0,100,size=(50,6))

In [122]:
zipped = {k:v  for k,v in zip(np.arange(1,51),scores0)}
a = ((k,*list(v)) for k,v in  zipped.items())

In [123]:
scores = np.array(list(a),dtype=subjects)

In [124]:
scores.shape

(50,)

In [125]:
scores

array([( 1, 42, 28, 35, 12, 31, 70), ( 2, 58, 85, 27, 65, 41, 44),
       ( 3, 61, 56,  5, 27, 27, 43), ( 4, 83, 29, 61, 74, 91, 88),
       ( 5, 61, 96,  0, 26, 61, 76), ( 6,  2, 69, 71, 26,  8, 61),
       ( 7, 36, 96, 50, 43, 23, 78), ( 8, 58, 31, 95, 87, 51, 61),
       ( 9, 57, 51, 11, 38,  1,  2), (10, 55, 80, 58,  1,  1, 91),
       (11, 53, 86, 95, 96,  0, 18), (12,  1, 52, 43, 89, 31, 69),
       (13, 31, 67, 54, 74, 55, 16), (14, 37, 23, 68, 97, 69, 85),
       (15, 10, 15, 96, 72, 58, 69), (16, 79, 92,  2, 19, 58, 35),
       (17, 18, 89, 66, 18, 19, 95), (18, 70, 51, 32, 39, 38, 81),
       (19,  0, 10, 91, 56, 88, 49), (20, 22, 30, 93, 41, 98,  6),
       (21, 15, 89, 59,  1,  0, 47), (22, 11, 68, 36, 31,  8, 98),
       (23, 18, 47, 79,  2, 19, 23), (24, 53, 32, 23, 74, 71, 35),
       (25, 37, 83, 98, 88, 98, 24), (26, 92, 17, 81, 65, 53, 34),
       (27, 79, 60, 40, 99, 32, 67), (28, 32, 13, 20, 47, 19,  7),
       (29,  6, 66, 16, 32, 47, 75), (30, 58, 85, 21, 29, 37, 

In [137]:
scores2 = np.vstack((scores['ala'],scores['agt'],scores['ca'],scores['E waste'],scores['green chem'],scores['rm']))
print(scores2.shape)
#gme = np.median(np.mean(scores[1:],axis=1)) # global median average
#scores = scores[np.mean(scores[1:],axis=1)>gme]
scores2 = scores2.T
#scores

(6, 50)


In [127]:
(scores0==scores2).all()

np.True_

In [128]:
a = scores2[np.arange(scores2.shape[0]),np.argmin(scores2,axis=1)] # array of min scores of each student
scores2[np.argsort(a)][-1::-1] # Students ranked/scores in descending order of their worst subject

array([[45, 52, 94, 98, 59, 96],
       [79, 60, 40, 99, 32, 67],
       [70, 51, 32, 39, 38, 81],
       [58, 31, 95, 87, 51, 61],
       [62, 84, 31, 86, 32, 66],
       [83, 29, 61, 74, 91, 88],
       [58, 85, 27, 65, 41, 44],
       [29, 96, 27, 63, 96, 68],
       [62, 85, 50, 24, 57, 62],
       [37, 83, 98, 88, 98, 24],
       [53, 32, 23, 74, 71, 35],
       [37, 23, 68, 97, 69, 85],
       [36, 96, 50, 43, 23, 78],
       [45, 23, 31, 46, 85, 22],
       [61, 21, 57, 57, 85, 48],
       [58, 85, 21, 29, 37, 50],
       [18, 89, 66, 18, 19, 95],
       [17, 24, 94, 53, 57, 66],
       [92, 17, 81, 65, 53, 34],
       [31, 67, 54, 74, 55, 16],
       [48, 16, 43, 91, 29, 92],
       [51, 41, 69, 14, 53, 59],
       [14, 91, 97, 65, 31, 86],
       [25, 98, 49, 24, 23, 12],
       [42, 28, 35, 12, 31, 70],
       [10, 15, 96, 72, 58, 69],
       [11, 68, 36, 31,  8, 98],
       [ 8, 42, 47, 38, 92, 41],
       [32, 13, 20, 47, 19,  7],
       [53,  7, 26, 26, 97, 20],
       [64

In [129]:
# Q3
top5 = np.argsort(scores2,axis=0)[:5]
print('top5 students in each subject by roll number')

for i in range(6):
    print('top5 in ',scores.dtype.names[i+1])
    print(top5[:,i])


top5 students in each subject by roll number
top5 in  ala
[18 11  5 49 28]
top5 in  agt
[34 42 30 43 48]
top5 in  ca
[ 4 39 15  2  8]
top5 in  E waste
[ 9 20 22 32  0]
top5 in  green chem
[10 20  9  8 48]
top5 in  rm
[ 8 19 27 41 12]


In [130]:
scores.dtype.names[0]

'roll no'

```
step1 : count ,how many values would make up 30 percent values of the total no of values
step2 : find index of students whose average score is in top 30 of the class (top30meanIndex)
step3 : access the scores of students in top30meanIndex and apply argsort to each student scores and get the lower 3 of them
step4 : now that we have the indexes of the lower 3 subject of each student , we just set them to 0
```

In [ ]:
#Q4
# top 30% highest average scores of students
r,c =scores2.shape
top30count = np.int32(np.multiply(r,c) * (30/100))
top30meanIndex = np.argsort(np.mean(scores2,axis=1))[:30]
scores2[np.arange(30)[:,None],np.argsort(scores2[top30meanIndex],axis=1)[:,:3]]=0

 

In [ ]:
scores2[:30] 

array([[42,  0, 35, 12,  0,  0],
       [58, 85,  0, 65,  0,  0],
       [ 0, 56,  5,  0,  0, 43],
       [ 0, 29, 61,  0,  0, 88],
       [61,  0,  0,  0,  0, 76],
       [ 2, 69,  0,  0,  0, 61],
       [36,  0, 50,  0, 23,  0],
       [58, 31,  0,  0,  0, 61],
       [57,  0, 11,  0,  1,  0],
       [55,  0,  0,  1,  0, 91],
       [53, 86, 95,  0,  0,  0],
       [ 0, 52, 43,  0,  0, 69],
       [ 0, 67,  0,  0, 55, 16],
       [ 0, 23, 68,  0,  0, 85],
       [10,  0,  0, 72, 58,  0],
       [79,  0,  0,  0, 58, 35],
       [ 0, 89, 66,  0, 19,  0],
       [70, 51,  0,  0,  0, 81],
       [ 0,  0,  0, 56,  0, 49],
       [ 0, 30,  0, 41,  0,  6],
       [15, 89,  0,  0,  0,  0],
       [ 0, 68, 36,  0,  0, 98],
       [ 0,  0, 79,  0, 19, 23],
       [53,  0,  0, 74, 71,  0],
       [ 0,  0, 98, 88, 98,  0],
       [ 0,  0, 81, 65, 53,  0],
       [ 0, 60,  0, 99, 32,  0],
       [32,  0, 20,  0,  0,  7],
       [ 0, 66, 16,  0,  0, 75],
       [ 0,  0, 21,  0, 37, 50]], dtype=int

In [133]:
# okay median gives the middle element
np.median([1,2,3,4,5,6])

np.float64(3.5)

---

$/begin{rough}

In [134]:
# I keep these cells here because it reminds me of what I,ve tried experimenting with
# Define a structured data type with field names and types
# 'name' -> string of max length 20
# 'age'  -> integer
# 'marks' -> float
student_dtype = np.dtype([
    ('name', 'U20'),   # Unicode string of length 20
    ('age', 'i4'),     # 32-bit integer
    ('marks', 'f4')    # 32-bit float
])

# Create a structured array with initial data
students = np.array([
    ['Alice', 21, 88.5],
    ['Bob', 19, 92.0],
    ['Charlie', 22, 79.5]
], dtype=student_dtype)

# Access entire columns by field name
print("Names:", students['name'])
print("Ages:", students['age'])
print("Marks:", students['marks'])

# Access a single row
print("First student record:", students[0])

# Modify a field
students[1]['marks'] = 95.0
print("Updated Bob's marks:", students[1])

# Filtering based on a condition
high_scorers = students[students['marks'] > 85]
print("High scorers:\n", high_scorers)

# Adding a new record (requires creating a new array)
new_student = np.array([('David', 20, 81.0)], dtype=student_dtype)
students = np.concatenate((students, new_student))
print("After adding David:\n", students)


ValueError: invalid literal for int() with base 10: 'Alice'

In [ ]:
a = (('Alice',),('in',),('wonderland',))
b = np.arange(3)
print(list(zip(*a,b,b)))


[('Alice', 'in', 'wonderland', np.int64(0), np.int64(0))]


$/end{rough}

---