# NumPy Speed Drill
Random seed used for this notebook: **7065044**
If you want to reproduce this exact drill set, run the generator with this seed.

In [1]:
import time, json
from pathlib import Path

SEED = 7065044
NUM_QUESTIONS = 25
STATS_FILE = "C:/Users/fbase/All_vscode_projects/numpyGithubRepo/daily-exercises/speed-drills/drill_stats.json" 

start_time = time.time()
print('Timer started')


Timer started


In [4]:
import numpy as np

### Question 1
Given A = np.array([8,3,15,1,9,12,7,5]), find unique elements.

In [5]:
A = np.array([8,3,15,1,9,12,7,5])
np.unique(A)

array([ 1,  3,  5,  7,  8,  9, 12, 15])

### Question 2
Given A = np.arange(1,26).reshape(5,5), extract the middle 3x3 block.

In [11]:
A = np.arange(1,26).reshape(5,5)
A[np.array([1,2,3])[:,None],np.array([1,2,3])]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [9]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Question 3
Given A = np.random.randint(0,20,(5,5)), compute diagonal sum.

In [12]:
A = np.random.randint(0,20,(5,5))

np.diag(A).sum()

np.int64(46)

In [13]:
A

array([[ 9, 19,  9,  2, 13],
       [15,  2,  3, 12,  2],
       [17, 15, 17,  1, 10],
       [16,  0,  1,  7,  5],
       [ 2, 18, 17,  9, 11]], dtype=int32)

### Question 4
Replace odd numbers with their negative.

In [14]:
np.where(A%2!=0,-A,A)

array([[ -9, -19,  -9,   2, -13],
       [-15,   2,  -3,  12,   2],
       [-17, -15, -17,  -1,  10],
       [ 16,   0,  -1,  -7,  -5],
       [  2,  18, -17,  -9, -11]], dtype=int32)

### Question 5
Given A = np.arange(1,13), reshape into 3x4.

In [15]:
A = np.arange(1,13).reshape(3,4)

In [19]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Question 6
Find row index containing maximum value.

In [26]:
a = np.sort(A,axis=1)
print("Row Index containing maximum value :",np.argsort(a[:,-1])[-1])

Row Index containing maximum value : 2


### Question 7
Given A = np.arange(-10,15), clip values to [-3,7].

In [36]:
A = np.arange(-10,15)
np.where((A<-3) | (A>7),0,A)

array([ 0,  0,  0,  0,  0,  0,  0, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,
        7,  0,  0,  0,  0,  0,  0,  0])

### Question 9
Given A = np.arange(12).reshape(4,3), square every element.

In [38]:
A = np.arange(12).reshape(4,3)
np.square(A)

array([[  0,   1,   4],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121]])

### Question 10
Given A = np.arange(12).reshape(4,3), multiply columns by [1,2,3].

In [106]:
# Couldn't solve , interpreted wrongly
A = np.arange(12).reshape(4,3)

# The answer depends on the interpretation of the question
arr = np.array([1,2,3])



In [108]:
# Answer I had to check
A * arr

# I dismissed this answer because i thought that if i did this then it would be multiplying each row by [1,2,3] , I was thinking I should multiply 
# element by the array [1,2,3] but that doesn't look like the answer either

array([[ 0,  2,  6],
       [ 3,  8, 15],
       [ 6, 14, 24],
       [ 9, 20, 33]])

### Question 11
Given A = np.arange(1,26).reshape(5,5), replace values >15 with 0.

In [64]:
A = np.arange(1,26).reshape(5,5)
A[A>15]=0

### Question 12
Extract indices of even numbers using np.where.

In [65]:
np.where(A%2==0)

(array([0, 0, 1, 1, 1, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4]),
 array([1, 3, 0, 2, 4, 1, 3, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]))

In [67]:
A[np.where(A%2==0)]

array([ 2,  4,  6,  8, 10, 12, 14,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

### Question 13
Extract elements greater than overall mean.

In [68]:
A[A>np.mean(A)]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [69]:
np.mean(A)

np.float64(4.8)

### Question 14
Extract values < -2 using a mask.

In [70]:
A[A<-2]

array([], dtype=int64)

### Question 15
Given A = np.arange(-10,15), find indices where value < -5.

In [71]:
A = np.arange(-10,15)
A[A<-5]

array([-10,  -9,  -8,  -7,  -6])

### Question 16
Given A = np.arange(-10,15), extract all positive numbers.

In [72]:
A = np.arange(-10,15)
A[A>0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Question 17
Extract anti-diagonal.

In [78]:
# diagonal of square matrix
A = np.array([[1, 0, 0],[0, 2, 0],[0, 0, 3]])

A[[2,1,0],[0,1,2]]

array([0, 2, 0])

### Question 18
Given A = np.arange(12).reshape(4,3), add vector [10,20,30] to each row.

In [81]:
A = np.arange(12).reshape(4,3)
A + [10,20,30]

array([[10, 21, 32],
       [13, 24, 35],
       [16, 27, 38],
       [19, 30, 41]])

In [80]:
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### Question 19
Given A = np.random.randint(0,20,(5,5)), compute standard deviation.

In [82]:
A = np.random.randint(0,20,(5,5))
np.std(A)

np.float64(5.58655528926368)

### Question 20
Given A = np.random.randint(0,20,(5,5)), count elements equal to row mean.

In [87]:
A = np.random.randint(0,20,(5,5))
a = A == np.mean(A,axis=1)
a


array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [91]:
A[a].shape[0] # count

0

In [85]:
A

array([[ 1,  9,  5, 18, 13],
       [13,  5,  2, 13,  1],
       [10, 13, 17, 15,  2],
       [19,  4,  3,  9, 16],
       [10, 15, 19,  4, 19]], dtype=int32)

In [86]:
np.mean(A,axis=1)

array([ 9.2,  6.8, 11.4, 10.2, 13.4])

### Question 21
Given A = np.arange(-10,15), compute the sum of positive numbers.

In [93]:
A = np.arange(-10,15)
np.sum(A[A>0])

np.int64(105)

### Question 22
Given A = np.arange(-10,15), replace numbers between 5 and 10 with 99.

In [94]:
A = np.arange(-10,15)
A[(A>=5) & (A<=10)] = 99

In [95]:
A

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,  99,  99,  99,  99,  99,  99,  11,  12,  13,  14])

### Question 23
Given A = np.arange(1,26).reshape(5,5), extract the entire 4th column.

In [96]:
A = np.arange(1,26).reshape(5,5)
A[:,3]

array([ 4,  9, 14, 19, 24])

### Question 24
Use ravel to convert reshaped A back to 1D.

In [103]:
# Didn't know this had to check answer
np.ravel(A,'F')

array([ 8,  3, 15,  1,  9, 12,  7,  5])

### Question 25
Given A = np.array([8,3,15,1,9,12,7,5]), sort descending.

In [99]:
A = np.array([8,3,15,1,9,12,7,5])
np.sort(A)[-1::-1]

array([15, 12,  9,  8,  7,  5,  3,  1])

## RUN THE NEXT CELL WHEN YOU FINISH ALL QUESTIONS

In [104]:
end_time = time.time()
total_time = end_time - start_time

stats_file = Path(STATS_FILE)

data = []
if stats_file.exists():
    data = json.loads(stats_file.read_text())

entry = {
    'seed': SEED,
    'questions': NUM_QUESTIONS,
    'total_time_seconds': total_time,
    'finished': True
}

data.append(entry)
stats_file.write_text(json.dumps(data, indent=2))

print('Session complete')
print(f'Total time: {total_time/60:.2f} minutes')


Session complete
Total time: 65.23 minutes
