# NumPy Speed Drill
Seed: **6341017**
Questions: **40**


In [1]:
import time, json
from pathlib import Path
from datetime import datetime
SEED = 6341017
NUM_QUESTIONS = 40
STATS_FILE = r"C:\Users\fbase\All_vscode_projects\numpyGithubRepo\daily-exercises\speed-drills\drill_stats.json"
TOPIC_COUNTS = {'broadcasting': 3, 'indexingSlicing': 8, 'searching': 11, 'counting': 5, 'sorting': 2, 'boolean': 3, 'statisticalAgrregation': 6, 'viewsCopies': 2}

start_time = time.time()
print('Timer started')


Timer started


In [2]:
import numpy as np

### Question 1 (broadcasting)
Given A = np.arange(12).reshape(4,3), add 5 to every element.

In [3]:
A = np.arange(12).reshape(4,3)
A + 5

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16]])

### Question 2 (indexingSlicing)
Given A = np.arange(1,26).reshape(5,5), extract the middle 3x3 block.

In [5]:
A = np.arange(1,26).reshape(5,5)
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [12]:
A[1:4,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

### Question 3 (searching)
Given A = np.array([[4,8,1],[6,3,9],[7,2,5]]), find the column containing the global minimum.

In [15]:
A = np.array([[4,8,1],[6,3,9],[7,2,5]])

In [19]:
np.where(A==np.min(A))[1]+1

array([3])

### Question 4 (searching)
Given A = np.array([1,4,7,2,5,8,3,6,9]), extract elements that are multiples of 3 using extract.

In [21]:
A = np.array([1,4,7,2,5,8,3,6,9])
np.extract(A%3==0,A)

array([3, 6, 9])

### Question 5 (searching)
Given A = np.array([np.nan,4,2,8,np.nan,5]), find the index of the minimum value ignoring NaNs using nanargmin.

In [22]:
A = np.array([np.nan,4,2,8,np.nan,5])
np.nanargmin(A)

np.int64(2)

### Question 6 (broadcasting)
Given A = np.arange(12).reshape(3,4), determine the result of A * np.array([[1],[2],[3]]).

In [23]:
A = np.arange(12).reshape(3,4)
A * np.array([[1],[2],[3]])
# 1st row multiplied by 1 , second row by 2 , third row by 3

array([[ 0,  1,  2,  3],
       [ 8, 10, 12, 14],
       [24, 27, 30, 33]])

### Question 7 (indexingSlicing)
Given A = np.arange(12).reshape(3,4), determine the shape of A[:,1:3].

In [24]:
A = np.arange(12).reshape(3,4)
A[:,1:3] # All rows and columns 1,2 , so 3,2

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

### Question 8 (counting)
Given A = np.array([[1,2,2],[3,3,4],[4,4,4]]), determine the most frequent value using bincount.

In [38]:
A = np.array([[1,2,2],[3,3,4],[4,4,4]])
a = np.bincount(A.reshape(-1))
print(f" Most occuring elment : {np.argmax(a)}")

 Most occuring elment : 4


### Question 9 (searching)
Given A = np.arange(1,13).reshape(3,4), use where to create an array that keeps even numbers and replaces odd numbers with 0.

In [39]:
A = np.arange(1,13).reshape(3,4)
np.where(A%2==0,A,0)

array([[ 0,  2,  0,  4],
       [ 0,  6,  0,  8],
       [ 0, 10,  0, 12]])

### Question 10 (sorting)
Given A = np.array([9,3,7,1,6]), use argpartition to move the smallest element to its correct position.

In [64]:
A = np.array([9,3,7,1,6])
A[np.argpartition(A,kth=0)]

array([1, 3, 6, 7, 9])

### Question 11 (searching)
Given A = np.array([[3,7,2],[9,5,1]]), compute the column index of the maximum value in each row using argmax with axis.

In [68]:
A = np.array([[3,7,2],[9,5,1]])
np.argmax(A,axis=1)

array([1, 0])

### Question 12 (indexingSlicing)
Given A = np.arange(12).reshape(3,4), determine the result of A[:,[True,False,True,False]].

In [69]:
A = np.arange(12).reshape(3,4)
A[:,[True,False,True,False]]
# A matric of A containing all rows but only 1st and 3rd row ( where its True )

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

### Question 13 (counting)
Given A = np.array([0,1,1,2,2,2,3,3]), compute frequencies of each value using bincount.

In [71]:
A = np.array([0,1,1,2,2,2,3,3])
for i,j in enumerate(np.bincount(A)):
    print(f"{i} comes {j} times")

0 comes 1 times
1 comes 2 times
2 comes 3 times
3 comes 2 times


### Question 14 (boolean)
Convert numbers between 2 and 6 into 50.

In [73]:
A[(A>2) & (A<6)]=50
A

array([ 0,  1,  1,  2,  2,  2, 50, 50])

### Question 15 (searching)
Given A = np.array([10,20,30,40,50]), find insertion indices for values [5,25,60] using searchsorted.

In [74]:
A = np.array([10,20,30,40,50])
np.searchsorted(A,v=[5,25,60],side='left')

array([0, 2, 5])

### Question 16 (indexingSlicing)
Given A = np.arange(12).reshape(3,4), determine whether A.T[0] is a view or copy.

In [78]:
A = np.arange(12).reshape(3,4)
# Didn't know this had to check
if np.shares_memory(A,A.T[0])==True:
    print('View')
else:
    print('Copy')

View


### Question 17 (statisticalAgrregation)
Given A = np.random.randint(0,50,(6,4)), compute range (max - min) of each row.

In [86]:
A = np.random.randint(0,50,(6,4))
np.max(A,axis=1) - A.min(axis=1)
# Assuming the question wants me to make an iterable by range() , an array is also an iterable , 
# cause max and min are both arrray so I can't do range(max - min) unless i do it seperately like apply range seperately to each element

array([23, 42, 15, 35, 29, 31], dtype=int32)

### Question 18 (statisticalAgrregation)
Given A = np.arange(1,21).reshape(4,5), compute row sums.

In [87]:
A = np.arange(1,21).reshape(4,5)
A.sum(axis=1)

array([15, 40, 65, 90])

### Question 19 (indexingSlicing)
Given A = np.arange(12).reshape(3,4), determine the result of A[:,A[0]>1].

In [88]:
A = np.arange(12).reshape(3,4)
# Return a boolean mask of 4 elements , and applied to columns so only those columns will show where the first col element is > 1
A[:,A[0]>1] 

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

### Question 20 (indexingSlicing)
Given A = np.arange(12).reshape(3,4), explain how ellipsis (...) expands during indexing.

In [ ]:
A = np.arange(12).reshape(3,4)
# ellipses assume you take all the remaining dimensions , like A[:,:] = A[...] , for a 3 dimensional array A[:,:,4] = A[...,4]
A[...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Question 21 (sorting)
Given A = np.array([7,2,9,4,1,5]), find the 3 smallest elements using partition.

In [ ]:
A = np.array([7,2,9,4,1,5])
np.partition(a=A,kth=1) 
# well for 1D array its sorting it fully

array([1, 2, 4, 5, 7, 9])

### Question 22 (searching)
Given A = np.array([10,20,30,40,50]), find insertion index of value 30 using searchsorted with side='left'.

In [97]:
A = np.array([10,20,30,40,50])
np.searchsorted(A,v=30,side='left')

np.int64(2)

### Question 23 (counting)
Given A = np.array([5,3,5,2,3,1,2,4]), return unique values along with their first occurrence indices.

In [98]:
A = np.array([5,3,5,2,3,1,2,4])
np.unique(A,return_index=True)

(array([1, 2, 3, 4, 5]), array([5, 3, 1, 7, 0]))

### Question 24 (indexingSlicing)
Given A = np.arange(12).reshape(3,4), determine the resulting shape after inserting a new axis with None.

In [102]:
A = np.arange(12).reshape(3,4)
# It would add a axis where I insert none so [None,...] , adds it at first dimension , [:,None,:] adds it at second dimension and so on
print(A[None,...],f"{A[None,...].shape}")
print(A[:,None,:],f"{A[:,None,:].shape}")

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]] (1, 3, 4)
[[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]] (3, 1, 4)


### Question 25 (indexingSlicing)
Given A = np.arange(9).reshape(3,3), determine the result of A[[0,1]][:,[1,2]].

In [103]:
A = np.arange(9).reshape(3,3)
# matrix containing first two rows and 2nd and 3rd columns
A[[0,1]][:,[1,2]]

array([[1, 2],
       [4, 5]])

### Question 26 (statisticalAgrregation)
Given A = np.random.randint(0,20,(5,5)), count elements greater than 10.

In [108]:
A = np.random.randint(0,20,(5,5))
np.count_nonzero(A[A>10])

np.int64(11)

In [105]:
A

array([[ 5,  9,  4, 13,  4],
       [ 3, 17, 19,  4, 17],
       [14, 14,  1,  9, 11],
       [ 6,  1,  3, 13, 12],
       [15, 10,  7, 14, 18]], dtype=int32)

### Question 27 (viewsCopies)
Given A = np.arange(12).reshape(3,4), use np.shares_memory(A,B) to verify memory sharing.

In [110]:
A = np.arange(12).reshape(3,4)
np.shares_memory(A,A[:])

True

### Question 28 (counting)
Given A = np.array([1,2,2,3,3,3,4]), verify that sum of bincount equals the length of the array.

In [111]:
A = np.array([1,2,2,3,3,3,4])
np.bincount(A).sum()==len(A)

np.True_

### Question 29 (boolean)
Replace values >5 with 100 using np.where.

In [113]:
np.where(A>5,100,A)

array([1, 2, 2, 3, 3, 3, 4])

### Question 30 (boolean)
Replace multiples of 3 with -3.

In [114]:
A[A%3==0]=-3

### Question 31 (statisticalAgrregation)
Given A = np.random.randint(0,50,(6,4)), compute variance of the entire array.

In [115]:
A = np.random.randint(0,50,(6,4))
A.var()

np.float64(189.63888888888889)

### Question 32 (counting)
Given A = np.array([0,0,1,1,1,2,2,3]), determine how many zeros appear using bincount.

In [118]:
A = np.array([0,0,1,1,1,2,2,3])
(np.bincount(A)==0).sum()

np.int64(0)

### Question 33 (searching)
Given A = np.array([[1,0,3],[0,5,0],[7,0,9]]), return the coordinates of non-zero elements using argwhere.

In [119]:
A = np.array([[1,0,3],[0,5,0],[7,0,9]])
np.argwhere(A!=0)

array([[0, 0],
       [0, 2],
       [1, 1],
       [2, 0],
       [2, 2]])

### Question 34 (searching)
Given A = np.array([4,7,1,9,3,6]), return the position of the minimum value using argmin.

In [120]:
A = np.array([4,7,1,9,3,6])
np.nanargmin(A)

np.int64(2)

### Question 35 (searching)
Given A = np.array([[5,2,np.nan],[1,7,3],[8,4,6]]), find the index of the maximum ignoring NaNs using nanargmax.

In [121]:
A = np.array([[5,2,np.nan],[1,7,3],[8,4,6]])
np.nanargmax(A)

np.int64(6)

### Question 36 (broadcasting)
Given A = np.arange(12).reshape(3,4), compute A + np.arange(3)[:,None].

In [123]:
A = np.arange(12).reshape(3,4)
A + np.arange(3)[:,None]


array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

### Question 37 (statisticalAgrregation)
Given A = np.random.randint(0,50,(6,4)), compute the sum of elements greater than 25.

In [124]:
A = np.random.randint(0,50,(6,4))
A[A>25].sum()

np.int64(520)

### Question 38 (searching)
Given A = np.array([[np.nan,2,5],[4,np.nan,1],[7,3,6]]), find the position of the maximum value ignoring NaNs using nanargmax.

In [ ]:
A = np.array([[np.nan,2,5],[4,np.nan,1],[7,3,6]])
np.nanargmax(A) # in the flattened 1D array

np.int64(6)

### Question 39 (viewsCopies)
Given A = np.arange(10), modify B = A[[2,3,4]]; B[:] = -1 and determine the resulting A.

In [ ]:
A = np.arange(10)
B = A[[2,3,4]]
B[:]=-1 # All elements of B are replaced by -1

### Question 40 (statisticalAgrregation)
Given A = np.random.randint(0,50,(6,4)), count elements below the median.

In [127]:
A = np.random.randint(0,50,(6,4))
np.count_nonzero(A[A<np.median(A)])

np.int64(11)

## RUN THE NEXT CELL WHEN YOU FINISH ALL QUESTIONS

In [128]:
end_time = time.time()
total_time = end_time - start_time
avg_time = total_time / NUM_QUESTIONS

stats_file = Path(STATS_FILE)
data = []
if stats_file.exists():
    data = json.loads(stats_file.read_text())

entry = {
    'date': datetime.now().isoformat(),
    'seed': SEED,
    'questions': NUM_QUESTIONS,
    'total_time_seconds': total_time,
    'avg_seconds_per_question': avg_time,
    'topics': TOPIC_COUNTS,
    'attempted_all': True
}

data.append(entry)
stats_file.write_text(json.dumps(data, indent=2))

print('Session complete')
print(f'Total time: {total_time/60:.2f} minutes')
print(f'Avg seconds/question: {avg_time:.2f}')


Session complete
Total time: 109.66 minutes
Avg seconds/question: 164.48
