# NumPy Speed Drill
Random seed used for this notebook: **4794217**
If you want to reproduce this exact drill set, run the generator with this seed.

In [1]:
import time, json
from pathlib import Path

SEED = 4794217
NUM_QUESTIONS = 25
STATS_FILE = "C:/Users/fbase/All_vscode_projects/numpyGithubRepo/daily-exercises/speed-drills/drill_stats.json" 

start_time = time.time()
print('Timer started')


Timer started


In [2]:
import numpy as np

### Question 1
Given A = np.arange(12).reshape(4,3), subtract row means from each row.

In [4]:
A = np.arange(12).reshape(4,3)
A - np.mean(A,axis=1)[:,None]

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

### Question 2
Given A = np.array([8,3,15,1,9,12,7,5]), get the 3 smallest values.

In [6]:
A = np.array([8,3,15,1,9,12,7,5])
np.sort(A)[:3]

array([1, 3, 5])

### Question 3
Given A = np.arange(12).reshape(4,3), normalize the array to 0-1 range.

In [7]:
A = np.arange(12).reshape(4,3)
A / np.sum(A)

array([[0.        , 0.01515152, 0.03030303],
       [0.04545455, 0.06060606, 0.07575758],
       [0.09090909, 0.10606061, 0.12121212],
       [0.13636364, 0.15151515, 0.16666667]])

### Question 4
Convert numbers between 2 and 6 into 50.

In [8]:
A[(A>1) & (A<7)] = 50

### Question 5
Given A = np.arange(-10,15), create an array where values >5 become 1 else 0.

In [9]:
A = np.arange(-10,15)
np.where(A > 5,1,0)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1])

### Question 6
Given A = np.arange(1,26).reshape(5,5), extract the four corner elements.

In [10]:
A = np.arange(1,26).reshape(5,5)
A [np.ix_([0,4],[4,0])]


array([[ 5,  1],
       [25, 21]])

### Question 7
Reshape into 3x4 then extract the second row.

In [13]:
np.arange(12).reshape(3,4)[1]

array([4, 5, 6, 7])

### Question 8
Given A = np.arange(12).reshape(4,3), multiply all elements by 2.

In [20]:
A = np.arange(12).reshape(4,3)
A * 2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

### Question 9
Extract anti-diagonal.

In [ ]:
A[[0,1,2],[2,1,0]]

array([2, 4, 6])

### Question 10
Reshape into 4x3 then transpose.

In [21]:
A.reshape((4,3)).T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

### Question 11
Given A = np.arange(1,26).reshape(5,5), reverse the row order.

In [22]:
A = np.arange(1,26).reshape(5,5)
A[-1::-1]

array([[21, 22, 23, 24, 25],
       [16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

### Question 12
Given A = np.random.randint(0,20,(5,5)), compute total sum.

In [23]:
A = np.random.randint(0,20,(5,5))
np.sum(A)

np.int64(244)

### Question 13
Given A = np.array([8,3,15,1,9,12,7,5]), find index of smallest value.

In [24]:
A = np.array([8,3,15,1,9,12,7,5])
np.argsort(A)

array([3, 1, 7, 6, 0, 4, 5, 2])

### Question 14
Extract values < -2 using a mask.

In [25]:
A[A<-2]

array([], dtype=int64)

### Question 15
Given A = np.arange(-10,15), compute the sum of positive numbers.

In [26]:
A = np.arange(-10,15)
np.sum(A[A>0])

np.int64(105)

### Question 16
Given A = np.random.randint(0,20,(5,5)), count elements equal to row mean.

In [48]:
A = np.random.randint(0,20,(5,5))

In [54]:
mean = np.mean(A,axis=1)[:,None]
a = (mean <= A)
b = (A <= mean)
print(a,'\n')
print(b,'\n')
print(a & b)
np.count_nonzero(a & b)

[[False  True False  True  True]
 [ True  True  True  True False]
 [ True  True False  True False]
 [False False  True False  True]
 [False  True False  True  True]] 

[[ True  True  True False False]
 [False False False False  True]
 [False False  True False  True]
 [ True  True False  True False]
 [ True False  True False False]] 

[[False  True False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


np.int64(1)

In [52]:
A

array([[14, 16, 15, 17, 18],
       [16, 15, 13, 19,  0],
       [10, 10,  1, 19,  8],
       [10,  9, 17,  9, 16],
       [ 1, 18,  0, 14, 14]], dtype=int32)

In [49]:
np.count_nonzero(A==np.mean(A,axis=1),axis=1)

array([0, 1, 0, 0, 0])

In [55]:
np.mean(A,axis=1)

array([16. , 12.6,  9.6, 12.2,  9.4])

### Question 17
Given A = np.arange(-6,10), replace negatives with 0 using np.where.

In [56]:
A = np.arange(-6,10)
np.where(A<0,0,A)

array([0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Question 18
Given A = np.array([8,3,15,1,9,12,7,5]), count elements greater than the mean.

In [57]:
A = np.array([8,3,15,1,9,12,7,5])
np.count_nonzero(A>np.mean(A))

np.int64(4)

### Question 19
Given A = np.random.randint(0,20,(5,5)), get indices of the max value.

In [58]:
A = np.array([8,3,15,1,9,12,7,5])
np.argmax(A)

np.int64(2)

### Question 20
Given A = np.random.randint(0,20,(5,5)), find max value in each row.

In [59]:
A = np.random.randint(0,20,(5,5))
np.max(A,axis=1)

array([15, 19, 17, 16, 17], dtype=int32)

In [60]:
A

array([[ 6,  5, 15,  9, 11],
       [12, 19,  7,  8, 10],
       [ 9,  2,  8,  4, 17],
       [ 1, 13, 16,  0, 14],
       [ 1, 10, 17,  3,  0]], dtype=int32)

### Question 21
Given A = np.arange(-10,15), find indices where value < -5.

In [61]:
### Question 21
A = np.arange(-10,15)
np.argwhere(A<-5)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [62]:
A

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14])

### Question 22
Replace values >15 with row mean.

In [ ]:
A = np.random.randint(0,20,(5,5))
A[A>15]=np.mean(A,axis=1)

# Question not suited for direct implemention / speed drills

ValueError: NumPy boolean array indexing assignment cannot assign 5 input values to the 6 output values where the mask is true

### Question 23
Replace multiples of 3 with -3.

In [64]:
A[A%3==0]=-3

### Question 24
Flatten a 3x4 reshaped version of A.

In [65]:
A.ravel()

array([-3, 17,  7,  8, 10,  1,  5,  4, 16, 10, -3, 11, 11, -3, -3, 14, 16,
       -3,  5, -3, 11, 16,  2, -3,  4], dtype=int32)

### Question 25
Given A = np.arange(1,26).reshape(5,5), extract all even numbers using boolean indexing.

In [66]:
A = np.arange(1,26).reshape(5,5)
A[A%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

## RUN THE NEXT CELL WHEN YOU FINISH ALL QUESTIONS

In [67]:
end_time = time.time()
total_time = end_time - start_time

stats_file = Path(STATS_FILE)

data = []
if stats_file.exists():
    data = json.loads(stats_file.read_text())

entry = {
    'seed': SEED,
    'questions': NUM_QUESTIONS,
    'total_time_seconds': total_time,
    'finished': True
}

data.append(entry)
stats_file.write_text(json.dumps(data, indent=2))

print('Session complete')
print(f'Total time: {total_time/60:.2f} minutes')


Session complete
Total time: 59.80 minutes
