# NumPy Speed Drill
Seed: **5819344**
Questions: **15**


In [ ]:
import time, json
from pathlib import Path
from datetime import datetime
SEED = 5819344
NUM_QUESTIONS = 15
STATS_FILE = r"C:\Users\fbase\All_vscode_projects\numpyGithubRepo\daily-exercises\speed-drills\drill_stats.json"
TOPIC_COUNTS = {'counting': 4, 'broadcasting': 2, 'sorting': 2, 'indexingSlicing': 3, 'searching': 3, 'viewsCopies': 1}

start_time = time.time()
print('Timer started')


Timer started


In [2]:
import numpy as np

### Question 1 (counting)
Given A = np.array([1,2,2,3,3,3,4,4,4,4]), find unique values using unique.

In [5]:
A = np.array([1,2,2,3,3,3,4,4,4,4])
np.unique(A)

array([1, 2, 3, 4])

### Question 2 (broadcasting)
Given A = np.arange(6).reshape(2,3) and B = np.array([[1],[2]]), determine the result of A + B.

In [6]:
A = np.arange(6).reshape(2,3) # 2 rows 3 cols
B = np.array([[1],[2]]) # 2 rows 1 col 
# B will stretch and becomes [[1,1,1],[2,2,3]]
# Now element wise addition will be done
A + B


array([[1, 2, 3],
       [5, 6, 7]])

### Question 3 (sorting)
Given names = np.array(['Tom','Alice','Bob','Alice']) and ages = np.array([25,30,25,22]), sort by age using argsort.

In [8]:
names = np.array(['Tom','Alice','Bob','Alice'])
ages = np.array([25,30,25,22])
names[np.argsort(ages)]

array(['Alice', 'Tom', 'Bob', 'Alice'], dtype='<U5')

### Question 4 (indexingSlicing)
Given A = np.arange(12).reshape(3,4), determine the shape of A[:,1:3].

In [ ]:
A = np.arange(12).reshape(3,4)
A[:,1:3] # All rows and columns 1,2

### Question 5 (counting)
Given A = np.array([1,2,2,3,3,3,4,4,4,4]), find how many times the value 3 appears using bincount.

In [11]:
A = np.array([1,2,2,3,3,3,4,4,4,4])
for index,val in enumerate(np.bincount(A)):
    print(f"{index} appears {val} times")

0 appears 0 times
1 appears 1 times
2 appears 2 times
3 appears 3 times
4 appears 4 times


### Question 6 (indexingSlicing)
Given A = np.arange(12).reshape(3,4), determine the result of A[:,[True,False,True,False]].

In [ ]:
A = np.arange(12).reshape(3,4)
# will print column with index 0 and 2

### Question 7 (searching)
Given A = np.array([[2,5,1],[8,3,7],[4,9,6]]), find indices of elements greater than the column mean using where.

In [18]:
A = np.array([[2,5,1],[8,3,7],[4,9,6]])
np.where(A>np.mean(A,axis=0))

(array([1, 1, 2, 2]), array([0, 2, 1, 2]))

### Question 8 (searching)
Given A = np.array([[1,4,7],[2,5,8],[3,6,9]]), replace values divisible by 3 with 0 using where.

In [20]:
A = np.array([[1,4,7],[2,5,8],[3,6,9]])
np.where(A%3==0,0,A)

array([[1, 4, 7],
       [2, 5, 8],
       [0, 0, 0]])

### Question 9 (viewsCopies)
Given A = np.arange(12).reshape(3,4), explain why chained indexing like A[:,1:3][:,0] can create copies.

In [ ]:
A = np.arange(12).reshape(3,4)
A[:,1:3][:,0]
# Well logically speaking A[:,1:3] is a view but if we we do  [:,0] to the view thats askings for the column with index 0 ( but like we are already on the 1st column of A ,
# soo 0th should mean another array)
# Because we are doing two seperate indexing operations , indexing on a slice/temporary result

array([1, 5, 9])

### Question 10 (broadcasting)
Given A = np.arange(12).reshape(3,4), explain why broadcasting does not copy data.

In [ ]:
# Broadcasting does not copy data because Numpy implements it by modifying array meta deta ( shape + strides ), not by allocating new memory
# Multiple elements share the same memory location because of this broadcasted arrays are normally read only views

### Question 11 (counting)
Given A = np.array([1,2,2,3,3,3,4,4,4,4]), determine how many times the value 3 appears using bincount.

In [24]:
A = np.array([1,2,2,3,3,3,4,4,4,4])
print(f"3 appears {np.bincount(A)[3]} times")


3 appears 3 times


### Question 12 (searching)
Given A = np.array([[2,4,6],[1,3,5],[7,8,9]]), extract all even elements using extract.

In [27]:
A = np.array([[2,4,6],[1,3,5],[7,8,9]])
np.extract(A%2==0,A)

array([2, 4, 6, 8])

### Question 13 (indexingSlicing)
Given A = np.arange(12).reshape(3,4), determine the shape of A[...,1:3].

In [28]:
# 3,2

### Question 14 (sorting)
Given A = np.array([7,2,9,4,1,5]), find the 3 largest elements using partition.

In [31]:
A = np.array([7,2,9,4,1,5])
np.partition(A,kth=4)[3:]

array([5, 7, 9])

### Question 15 (counting)
Given A = np.array([[1,2,2],[3,3,4],[4,4,4]]), find unique rows using unique with axis=0.

In [34]:
A = np.array([[1,2,2],[1,2,2],[3,3,4],[4,4,4]])
np.unique(A,axis=0)

array([[1, 2, 2],
       [3, 3, 4],
       [4, 4, 4]])

## RUN THE NEXT CELL WHEN YOU FINISH ALL QUESTIONS

In [35]:
end_time = time.time()
total_time = end_time - start_time
avg_time = total_time / NUM_QUESTIONS

stats_file = Path(STATS_FILE)
data = []
if stats_file.exists():
    data = json.loads(stats_file.read_text())

entry = {
    'date': datetime.now().isoformat(),
    'seed': SEED,
    'questions': NUM_QUESTIONS,
    'total_time_seconds': total_time,
    'avg_seconds_per_question': avg_time,
    'topics': TOPIC_COUNTS,
    'attempted_all': True
}

data.append(entry)
stats_file.write_text(json.dumps(data, indent=2))

print('Session complete')
print(f'Total time: {total_time/60:.2f} minutes')
print(f'Avg seconds/question: {avg_time:.2f}')


Session complete
Total time: 41.83 minutes
Avg seconds/question: 167.31
