# NumPy Speed Drill
Seed: **5158520**
Questions: **15**


In [2]:
import time, json
from pathlib import Path
from datetime import datetime
from datetime import datetime
SEED = 5158520
NUM_QUESTIONS = 15
STATS_FILE = r"C:\Users\fbase\All_vscode_projects\numpyGithubRepo\daily-exercises\speed-drills\drill_stats.json"
TOPIC_COUNTS = {'sorting': 3, 'searching': 3, 'broadcasting': 2, 'statisticalAgrregation': 2, 'indexingSlicing': 3, 'dtypes': 1, 'boolean': 1}

start_time = time.time()

start_timestamp = datetime.now()
print('Timer started')


Timer started


In [3]:
import numpy as np

### Question 1 (sorting)
Given A = np.array([9,3,7,1,6]), retrieve the indices of the 2 largest values using argpartition.

In [11]:
A = np.array([9,3,7,1,6])
np.argpartition(A,kth=0)[-2::]

array([2, 0])

### Question 2 (searching)
Given A = np.array([[2,0,3],[0,1,0],[4,0,5]]), extract all non-zero values using nonzero.

In [13]:
A = np.array([[2,0,3],[0,1,0],[4,0,5]])
A[np.nonzero(A)]

array([2, 3, 1, 4, 5])

### Question 3 (broadcasting)
Given A = np.arange(12).reshape(3,4), compute A + np.arange(4).

In [14]:
A = np.arange(12).reshape(3,4)
A + np.arange(4)

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

### Question 4 (searching)
Given A = np.array([5,12,7,18,3,20]), extract elements greater than 10 using extract.

In [16]:
A = np.array([5,12,7,18,3,20])
A[np.extract(A,A>10)]

array([12, 18, 20])

### Question 5 (statisticalAgrregation)
Given A = np.random.randint(0,50,(6,4)), compute the 75th percentile of all elements.

In [17]:
A = np.random.randint(0,50,(6,4))
np.percentile(a=A,q=75)

np.float64(38.75)

### Question 6 (indexingSlicing)
Given A = np.arange(12).reshape(3,4), determine the shape of A[[0,2],[1,3]].

In [19]:
A = np.arange(12).reshape(3,4)
# shape 1,2
A[[0,2],[1,3]]

array([ 1, 11])

### Question 7 (indexingSlicing)
Given A = np.arange(10), compute A[::-1] and determine if it is a view or copy.

In [21]:
A = np.arange(10)
# It should be a view because its slicing only
np.shares_memory(A[::-1],A)

True

### Question 8 (sorting)
Given A = np.array([1+2j,3+1j,2+4j,1+1j]), sort complex numbers using np.sort and observe ordering.

In [23]:
A = np.array([1+2j,3+1j,2+4j,1+1j])
np.sort(A)
# yes Real component is compared then the imaginary component

array([1.+1.j, 1.+2.j, 2.+4.j, 3.+1.j])

### Question 9 (searching)
Given A = np.array([[2,4,6],[1,3,5],[7,8,9]]), extract all even elements using extract.

In [27]:
A = np.array([[2,4,6],[1,3,5],[7,8,9]])
A[np.extract(A,A%2==0).reshape(A.shape)]

array([2, 4, 6, 8])

### Question 10 (dtypes)
Given A = np.array([1,2,3], dtype=np.int32), compute total bytes consumed by the array.

In [ ]:
A = np.array([1,2,3], dtype=np.int64)
print("Item size tell the bytes consumed by each element of array , and each bytes has 8 bits so thats 8 * 4 = 32 bits which is equal to the 32 in int32")
print("total bytes consumed by the array :",A.itemsize*len(A))

Item size tell the bytes consumed by each element of array , and each bytes has 8 bits so thats 8 * 4 = 32 bits which is equal to the 32 in int32
total bytes consumed by the array : 8


### Question 11 (sorting)
Given X = np.array([1,1,2,2]) and Y = np.array([3,1,4,2]), explain why the order of keys matters in lexsort.

In [35]:
X = np.array([1,1,2,2])
Y = np.array([3,1,4,2])
print("Order of keys matter because the last key is the primary sorting key which is getting sorting")
print("If there are equal values then the values in the previous key ( that comes before it ) are compared to sort the keys of the primary key")
print("and lexsort returns the index")
print("See the differnence ")
print("np.lexsort((X,Y))",f"index :{np.lexsort((X,Y))}",f"sorted : {Y[np.lexsort((X,Y))]}")
print("np.lexsort((Y,X))",f"index :{np.lexsort((Y,X))}",f"sorted : {X[np.lexsort((Y,X))]}")

Order of keys matter because the last key is the primary sorting key which is getting sorting
If there are equal values then the values in the previous key ( that comes before it ) are compared to sort the keys of the primary key
and lexsort returns the index
See the differnence 
np.lexsort((X,Y)) index :[1 3 0 2] sorted : [1 2 3 4]
np.lexsort((Y,X)) index :[1 0 3 2] sorted : [1 1 2 2]


### Question 12 (boolean)
Find row index containing maximum value.

In [40]:
A = np.arange(12).reshape(4,3)
np.sum(A,axis=1).argmax()

np.int64(3)

### Question 13 (broadcasting)
Given A = np.arange(12).reshape(4,3), compute row sums.

In [41]:
A.sum(axis=1)

array([ 3, 12, 21, 30])

### Question 14 (indexingSlicing)
Given A = np.arange(12).reshape(3,4), explain why chained indexing like A[:,1:3][:,0] may lead to confusion.

In [42]:
A = np.arange(12).reshape(3,4)
# chained indexing like that is giving two different slicing on the columns of A 
# The second slicing creates a copy because its slicing a slice , which gets complicated to do without creating new memory blocks
# and slicing is supposed to return views , when it doesn't it might lead to confusion

### Question 15 (statisticalAgrregation)
Given A = np.random.randint(0,50,(6,4)), find the column with the largest sum.

In [46]:
A = np.random.randint(0,50,(6,4))
print("column index with the largest sum :",np.argmax(np.sum(A,axis=0)))


column index with the largest sum : 1


## RUN THE NEXT CELL WHEN YOU FINISH ALL QUESTIONS

In [47]:
end_time = time.time()
end_timestamp = datetime.now()
total_time = end_time - start_time
avg_time = total_time / NUM_QUESTIONS

stats_file = Path(STATS_FILE)
data = []
if stats_file.exists():
    data = json.loads(stats_file.read_text())

entry = {
    'date': datetime.now().isoformat(),
    'start_time':start_timestamp.isoformat(),
    'end_time':end_timestamp.isoformat(),
    'seed': SEED,
    'questions': NUM_QUESTIONS,
    'total_time_seconds': total_time,
    'avg_seconds_per_question': avg_time,
    'topics': TOPIC_COUNTS,
    'attempted_all': True
}

data.append(entry)
stats_file.write_text(json.dumps(data, indent=2))

print('Session complete')
print(f'Total time: {total_time/60:.2f} minutes')
print(f'Avg seconds/question: {avg_time:.2f}')


Session complete
Total time: 33.58 minutes
Avg seconds/question: 134.34
