# NumPy Speed Drill
Seed: **5892413**
Questions: **15**


In [1]:
import time, json
from pathlib import Path
from datetime import datetime
from datetime import datetime
SEED = 5892413
NUM_QUESTIONS = 15
STATS_FILE = r"C:\Users\fbase\All_vscode_projects\numpyGithubRepo\daily-exercises\speed-drills\drill_stats.json"
TOPIC_COUNTS = {'statisticalAgrregation': 3, 'searching': 5, 'boolean': 2, 'broadcasting': 2, 'counting': 1, 'dtypes': 2}

start_time = time.time()

start_timestamp = datetime.now()
print('Timer started')


Timer started


In [2]:
import numpy as np

### Question 1 (statisticalAgrregation)
Given A = np.random.randint(0,50,(6,4)), count elements below the median.

In [3]:
A = np.random.randint(0,50,(6,4))
np.sum(A<np.median(A))

np.int64(12)

### Question 2 (searching)
Given A = np.array([10,20,30,30,30,40]), find insertion index for 30 using searchsorted with side='left'.

In [4]:
A = np.array([10,20,30,30,30,40])
np.searchsorted(A,v=30,side='left')

np.int64(2)

### Question 3 (searching)
Given A = np.array([[3,0,5],[0,0,2],[7,0,1]]), return coordinates of elements greater than 3 using argwhere.

In [5]:
A = np.array([[3,0,5],[0,0,2],[7,0,1]])
np.argwhere(A>3)

array([[0, 2],
       [2, 0]])

### Question 4 (searching)
Given A = np.array([[3,0,5],[0,0,2],[7,0,1]]), find coordinates of all zero elements using argwhere.

In [6]:
A = np.array([[3,0,5],[0,0,2],[7,0,1]])
np.argwhere(A==0)

array([[0, 1],
       [1, 0],
       [1, 1],
       [2, 1]])

### Question 5 (boolean)
Given A = np.arange(-10,15), extract all positive numbers.

In [8]:
A = np.arange(-10,15)
A[A>0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Question 6 (statisticalAgrregation)
Given A = np.random.randint(0,50,(6,4)), compute cumulative sum along rows.

In [9]:
A = np.random.randint(0,50,(6,4))
np.cumulative_sum(A,axis=1)

array([[ 46,  67,  72,  84],
       [ 42,  70, 110, 138],
       [ 11,  54,  74, 108],
       [  3,   4,  32,  46],
       [ 21,  42,  62,  96],
       [ 22,  49,  78, 124]])

### Question 7 (broadcasting)
Given A = np.arange(6).reshape(2,3), compute A - A.mean(axis=1, keepdims=True).

In [ ]:
A = np.arange(6).reshape(2,3)
A - A.mean(axis=1, keepdims=True) # Intresting

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.]])

### Question 8 (statisticalAgrregation)
Given A = np.random.randint(0,50,(6,4)), compute the 25th percentile for each column.

In [14]:
A = np.random.randint(0,50,(6,4))
np.percentile(a=A,q=25)

np.float64(24.25)

### Question 9 (counting)
Given A = np.array([1,2,2,3,3,3,4,4,4,4]), find unique values and their counts using unique.

In [18]:
A = np.array([1,2,2,3,3,3,4,4,4,4])
np.bincount(A)

array([0, 1, 2, 3, 4])

### Question 10 (dtypes)
Given A = np.array([1,2,3], dtype=np.int8), cast to float using astype and verify the new dtype.

In [21]:
A = np.array([1,2,3], dtype=np.int8)
A= A.astype(np.float32)
print(A.dtype)

float32


### Question 11 (searching)
Given A = np.array([[1,4,7],[2,5,8],[3,6,9]]), find indices of values divisible by 3 using where.

In [22]:
A = np.array([[1,4,7],[2,5,8],[3,6,9]])
np.where(A%3==0)

(array([2, 2, 2]), array([0, 1, 2]))

### Question 12 (dtypes)
Given A = np.array([255], dtype=np.uint8), compute A + 1 and observe overflow behavior.

In [23]:
A = np.array([255], dtype=np.uint8)
A + 1

array([0], dtype=uint8)

### Question 13 (searching)
Given A = np.array([[1,0,3],[0,5,0],[7,0,9]]), return the coordinates of non-zero elements using argwhere.

In [24]:
A = np.array([[1,0,3],[0,5,0],[7,0,9]])
np.argwhere(A!=0)

array([[0, 0],
       [0, 2],
       [1, 1],
       [2, 0],
       [2, 2]])

### Question 14 (broadcasting)
Find positions of multiples of 5.

In [32]:
A%5==0

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [36]:
b = np.arange(3).reshape(3,1) * np.ones(shape=(3,3))
a = np.arange(3).reshape(1,3) * np.ones(shape=(3,3))
print("row index :",a[A%5==0],"Column index :",b[A%5==0])


row index : [1.] Column index : [1.]


### Question 15 (boolean)
Replace numbers divisible by 4 with 999.

In [25]:
A[A%4==0] = 999

## RUN THE NEXT CELL WHEN YOU FINISH ALL QUESTIONS

In [ ]:
end_time = time.time()
end_timestamp = datetime.now()
total_time = end_time - start_time
avg_time = total_time / NUM_QUESTIONS

stats_file = Path(STATS_FILE)
data = []
if stats_file.exists():
    data = json.loads(stats_file.read_text())

entry = {
    'date': datetime.now().isoformat(),
    'start_time':start_timestamp.isoformat(),
    'end_time':end_timestamp.isoformat(),
    'seed': SEED,
    'questions': NUM_QUESTIONS,
    'total_time_seconds': total_time,
    'avg_seconds_per_question': avg_time,
    'topics': TOPIC_COUNTS,
    'attempted_all': True
}

data.append(entry)
stats_file.write_text(json.dumps(data, indent=2))

print('Session complete')
print(f'Total time: {total_time/60:.2f} minutes')
print(f'Avg seconds/question: {avg_time:.2f}')
