# NumPy Speed Drill
Random seed used for this notebook: **5108292**
If you want to reproduce this exact drill set, run the generator with this seed.

In [1]:
import time, json
from pathlib import Path

SEED = 5108292
NUM_QUESTIONS = 20
STATS_FILE = "C:/Users/fbase/All_vscode_projects/numpyGithubRepo/daily-exercises/speed-drills/drill_stats.json" 

start_time = time.time()
print('Timer started')


Timer started


In [2]:
import numpy as np

### Question 1
Given A = np.arange(1,21).reshape(4,5), compute row sums.

In [3]:
A = np.arange(1,21).reshape(4,5)
np.sum(A,axis=1)

array([15, 40, 65, 90])

### Question 2
Given A = np.arange(1,26).reshape(5,5), extract the diagonal elements.

In [5]:
A = np.arange(1,26).reshape(5,5)
np.diag(A)

array([ 1,  7, 13, 19, 25])

### Question 3
Given A = np.arange(-10,15), extract numbers divisible by 3.

In [6]:
A = np.arange(-10,15)
A[A%3==0]

array([-9, -6, -3,  0,  3,  6,  9, 12])

### Question 4
Given A = np.arange(1,26).reshape(5,5), extract the last two rows.

In [8]:
A = np.arange(1,26).reshape(5,5)
A[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Question 5
Compute difference between each element and column mean.

In [9]:
cmean = np.mean(A,axis=0)
A - cmean

array([[-10., -10., -10., -10., -10.],
       [ -5.,  -5.,  -5.,  -5.,  -5.],
       [  0.,   0.,   0.,   0.,   0.],
       [  5.,   5.,   5.,   5.,   5.],
       [ 10.,  10.,  10.,  10.,  10.]])

In [10]:
cmean

array([11., 12., 13., 14., 15.])

In [11]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Question 6
Given A = np.array([8,3,15,1,9,12,7,5]), get the 3 largest values.

In [12]:
A = np.array([8,3,15,1,9,12,7,5])
np.sort(A)[[-3,-2,-1]]

array([ 9, 12, 15])

### Question 7
Given A = np.random.randint(0,20,(5,5)), compute total sum.

In [14]:
A = np.random.randint(0,20,(5,5))
np.sum(A)

np.int64(228)

### Question 8
Extract anti-diagonal.

In [22]:
A[np.arange(5),np.arange(4,-1,-1)]

array([15,  6, 13, 19,  5], dtype=int32)

In [16]:
A

array([[ 6, 10, 12,  1, 15],
       [ 9, 11, 13,  6,  9],
       [ 3, 16, 13,  9,  7],
       [ 2, 19,  8, 12,  9],
       [ 5, 12, 19,  0,  2]], dtype=int32)

In [20]:
np.arange(4,-1,-1)

array([4, 3, 2, 1, 0])

### Question 9
Normalize each row by its row sum.

In [23]:
A / np.sum(A,axis=1)

array([[0.13636364, 0.20833333, 0.25      , 0.02      , 0.39473684],
       [0.20454545, 0.22916667, 0.27083333, 0.12      , 0.23684211],
       [0.06818182, 0.33333333, 0.27083333, 0.18      , 0.18421053],
       [0.04545455, 0.39583333, 0.16666667, 0.24      , 0.23684211],
       [0.11363636, 0.25      , 0.39583333, 0.        , 0.05263158]])

### Question 10
Given A = np.array([8,3,15,1,9,12,7,5]), find positions where value > 8.

In [24]:
A = np.array([8,3,15,1,9,12,7,5])
np.nonzero(A>8)

(array([2, 4, 5]),)

### Question 11
Convert A into a column vector.

In [30]:
A[:,None]

array([[ 8],
       [ 3],
       [15],
       [ 1],
       [ 9],
       [12],
       [ 7],
       [ 5]])

### Question 12
Given A = np.arange(12).reshape(4,3), subtract row means from each row.

In [31]:
A = np.arange(12).reshape(4,3)
A - np.sum(A,axis=1)[:,None]

array([[ -3,  -2,  -1],
       [ -9,  -8,  -7],
       [-15, -14, -13],
       [-21, -20, -19]])

### Question 13
Given A = np.random.randint(0,20,(5,5)), get indices of the max value.

In [33]:
A = np.random.randint(0,20,(5,5))
np.where(A==np.max(A))

(array([0, 4]), array([1, 1]))

### Question 14
Convert numbers between 2 and 6 into 50.

In [34]:
A[(A>=2) & (A<=6)]=50

### Question 15
Given A = np.array([8,3,15,1,9,12,7,5]), find index of largest value.

In [35]:
A = np.array([8,3,15,1,9,12,7,5])
np.argmax(A)

np.int64(2)

### Question 16
Given A = np.arange(-6,10), replace negatives with 0 using np.where.

In [36]:
A = np.arange(-6,10)
np.where(A<0,0,A)

array([0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Question 17
Given A = np.random.randint(0,20,(5,5)), count elements greater than 10.

In [37]:
A = np.random.randint(0,20,(5,5))
np.count_nonzero(A>10)

np.int64(11)

### Question 18
Given A = np.arange(12).reshape(4,3), square every element.

In [38]:
A = np.arange(12).reshape(4,3)
A*2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

### Question 19
Given A = np.arange(1,26).reshape(5,5), reverse the row order.

In [40]:
A = np.arange(1,26).reshape(5,5)
A[-1::-1]

array([[21, 22, 23, 24, 25],
       [16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

### Question 20
Given A = np.random.randint(0,20,(5,5)), compute diagonal sum.

In [41]:
A = np.random.randint(0,20,(5,5))
np.diag(A).sum()

np.int64(50)

## RUN THE NEXT CELL WHEN YOU FINISH ALL QUESTIONS

In [42]:
end_time = time.time()
total_time = end_time - start_time

stats_file = Path(STATS_FILE)

data = []
if stats_file.exists():
    data = json.loads(stats_file.read_text())

entry = {
    'seed': SEED,
    'questions': NUM_QUESTIONS,
    'total_time_seconds': total_time,
    'finished': True
}

data.append(entry)
stats_file.write_text(json.dumps(data, indent=2))

print('Session complete')
print(f'Total time: {total_time/60:.2f} minutes')


Session complete
Total time: 18.59 minutes
