# NumPy Speed Drill
Seed: **8234051**
Questions: **20**


In [1]:
import time, json
from pathlib import Path
from datetime import datetime
SEED = 8234051
NUM_QUESTIONS = 20
STATS_FILE = r"C:\Users\fbase\All_vscode_projects\numpyGithubRepo\daily-exercises\speed-drills\drill_stats.json"
TOPIC_COUNTS = {'dtypes': 2, 'sorting': 4, 'searching': 5, 'broadcasting': 4, 'statisticalAgrregation': 2, 'counting': 3}

start_time = time.time()
print('Timer started')


Timer started


In [2]:
import numpy as np

### Question 1 (dtypes)
Given A = np.array([1,2,3], dtype=np.int32), compute A // 2 and determine the resulting dtype.

In [6]:
A = np.array([1,2,3], dtype=np.int32)
print(A//2)
print((A//2).dtype)

[0 1 1]
int32


### Question 2 (sorting)
Given A = np.array([50,20,40,10,30]), return indices that would sort the array using argsort.

In [7]:
A = np.array([50,20,40,10,30])
np.argsort(A)

array([3, 1, 4, 2, 0])

### Question 3 (searching)
Given A = np.arange(1,16).reshape(3,5), extract elements greater than the row mean using where.

In [13]:
A = np.arange(1,16).reshape(3,5)
A
A[np.where(A>np.mean(A,axis=1)[:,None])]

array([ 4,  5,  9, 10, 14, 15])

### Question 4 (sorting)
Given A = np.array([50,20,40,10,30]), reorder the array using argsort.

In [14]:
A = np.array([50,20,40,10,30])
A[np.argsort(A)]

array([10, 20, 30, 40, 50])

### Question 5 (broadcasting)
Given A = np.arange(12).reshape(3,4), determine why A + np.arange(3) fails.

In [ ]:
"""Because we can np.arange(3) is a 1D array it can only stretch downwards but its missing a fourth value , so either add a fourth value or do ( noting is matching not rows or cols)
np.arange(3)[:,None] because now it can stretch alone the columns as the no of rows is same no
"""

### Question 6 (statisticalAgrregation)
Given A = np.random.randint(0,20,(5,5)), compute diagonal sum.

In [ ]:
A = np.random.randint(0,20,(5,5))
np.diag(A).sum()

8

### Question 7 (broadcasting)
Given A = np.arange(12).reshape(3,4), compute A + np.arange(4).

In [18]:
A = np.arange(12).reshape(3,4)
A + np.arange(4)

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

### Question 8 (dtypes)
Given A = np.array([1,2,3], dtype=np.int32), explain the difference between dtype and itemsize.

In [24]:
A = np.array([1,2,3], dtype=np.int32)
A
"""dtype is the datatype of elements in the array , since numpy array can only have homogenous elements there is only 1 dtype for a normal array
   itemsize is the memory usage per value of the array , no of bytes per value and each byte = 8 bits
"""
A.itemsize


4

### Question 9 (searching)
Given A = np.array([[2,4,6],[1,3,5],[7,8,9]]), extract all even elements using extract.

In [26]:
A = np.array([[2,4,6],[1,3,5],[7,8,9]])
np.extract(A%2==0,A)

array([2, 4, 6, 8])

### Question 10 (counting)
Given A = np.array([1,2,2,3,3,3,4,4,4,4]), return unique values and their counts.

In [31]:
A = np.array([1,2,2,3,3,3,4,4,4,4])
np.unique(A,return_counts=True)

(array([1, 2, 3, 4]), array([1, 2, 3, 4]))

### Question 11 (counting)
Given A = np.array([1,0,2,0,3,0,4]), count the number of non-zero elements using count_nonzero.

In [32]:
A = np.array([1,0,2,0,3,0,4])
np.count_nonzero(A)

np.int64(4)

### Question 12 (searching)
Given A = np.array([np.nan,4,2,8,np.nan,5]), find the index of the minimum value ignoring NaNs using nanargmin.

In [35]:
A = np.array([np.nan,4,2,8,np.nan,5])
np.nanargmin(A)

np.int64(2)

### Question 13 (sorting)
Given A = np.array([[4,2,7],[1,5,3]]), sort each column using np.sort with axis.

In [37]:
A = np.array([[4,2,7],[1,5,3]])
np.sort(A,axis=0)

array([[1, 2, 3],
       [4, 5, 7]])

### Question 14 (searching)
Given A = np.array([10,20,30,40,50]), find the insertion index for value 35 using searchsorted.

In [38]:
A = np.array([10,20,30,40,50])
np.searchsorted(A,v=35)

np.int64(3)

### Question 15 (sorting)
Given scores = np.array([85,90,85,92]) and ids = np.array([3,1,4,2]), sort by scores and break ties using ids with lexsort.

In [40]:
scores = np.array([85,90,85,92])
ids = np.array([3,1,4,2])
np.lexsort((ids,scores))

array([0, 2, 1, 3])

### Question 16 (broadcasting)
Given A = np.arange(12).reshape(3,4), add column indices to each column using broadcasting.

In [43]:
A = np.arange(12).reshape(3,4)
A + np.arange(3)[:,None]

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

### Question 17 (broadcasting)
Given A = np.arange(12).reshape(3,4), determine the result of A * np.array([1,2,3,4]).

In [44]:
A = np.arange(12).reshape(3,4)
A * np.array([1,2,3,4])

array([[ 0,  2,  6, 12],
       [ 4, 10, 18, 28],
       [ 8, 18, 30, 44]])

### Question 18 (searching)
Given A = np.array([10,20,30,30,30,40]), find insertion index for 30 using searchsorted with side='right'.

In [46]:
A = np.array([10,20,30,30,30,40])
np.searchsorted(A,v=30,side='right')

np.int64(5)

### Question 19 (statisticalAgrregation)
Given A = np.arange(1,21).reshape(4,5), compute row sums.

In [47]:
A = np.arange(1,21).reshape(4,5)
np.sum(A,axis=1)

array([15, 40, 65, 90])

### Question 20 (counting)
Given A = np.array([1,2,2,3,3,3,4]), verify that sum of bincount equals the length of the array.

In [50]:
A = np.array([1,2,2,3,3,3,4])
np.bincount(A).sum()==len(A)

np.True_

## RUN THE NEXT CELL WHEN YOU FINISH ALL QUESTIONS

In [51]:
end_time = time.time()
total_time = end_time - start_time
avg_time = total_time / NUM_QUESTIONS

stats_file = Path(STATS_FILE)
data = []
if stats_file.exists():
    data = json.loads(stats_file.read_text())

entry = {
    'date': datetime.now().isoformat(),
    'seed': SEED,
    'questions': NUM_QUESTIONS,
    'total_time_seconds': total_time,
    'avg_seconds_per_question': avg_time,
    'topics': TOPIC_COUNTS,
    'attempted_all': True
}

data.append(entry)
stats_file.write_text(json.dumps(data, indent=2))

print('Session complete')
print(f'Total time: {total_time/60:.2f} minutes')
print(f'Avg seconds/question: {avg_time:.2f}')


Session complete
Total time: 39.97 minutes
Avg seconds/question: 119.92
